backend:
  name: github
  repo: 20251p1ctw/1p1c
  branch: main
  base_url: https://sveltia-cms-auth.a0930619084.workers.dev  # 您的代理網址

media_folder: "images"
public_folder: "/images"

collections:
  - name: "articles"
    label: "自訂文章"
    folder: "articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "日期", name: "date", widget: "datetime" }
      - { label: "內容（支援富文字、圖片、列表等）", name: "body", widget: "markdown" }
      - { label: "特色圖片", name: "image", widget: "image", required: false }
      - { label: "簡短描述", name: "description", widget: "text", required: false }